name: Gradle Sample

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

  detekt:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Run detekt
      run: ./gradlew detekt

  tests:
    needs: detekt
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Run tests
      run: ./gradlew test

  build:
    needs: tests
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
      
    - name: Run build
      run: ./gradlew build
